/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.XE;

import DTO.GUIXE_DTO;
import MODEL.DANG_KI_HINH_THUC_XE;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HUU77
 */
public class DS_HINH_THUC_GUI_XE extends javax.swing.JPanel {

    /**
     * Creates new form DS_HINH_THUC_GUI_XE
     */
    public DS_HINH_THUC_GUI_XE() {
        initComponents();
        showDS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jtxtSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbDS = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1279, 559));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("ĐẶT LẠI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("TÌM KIẾM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("DANH SÁCH");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(254, 254, 254)
                        .addComponent(jtxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(104, 104, 104)
                        .addComponent(jButton1)))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jtxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(56, 56, 56))
        );

        jtbDS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtbDS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1267, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String textSearch = jtxtSearch.getText();
        
        showDATA(textSearch);


    }//GEN-LAST:event_jButton2ActionPerformed
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jtxtSearch.setText("");
        showDS();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtbDS;
    private javax.swing.JTextField jtxtSearch;
    // End of variables declaration//GEN-END:variables
public void showDS() {
        DefaultTableModel model = new DefaultTableModel();
        model.setRowCount(0);

        /* Tạo mới Vector chứa Column Header */
        Vector column = new Vector();
        column.add("MA THẺ");
        column.add("BIỂN SỐ XE");
        column.add("HÌNH THỨC");
        column.add("NGAY DANG KI");
        column.add("NGAY HET HAN");
        column.add("TIỀN ĐÃ THU");
        column.add("TÌNH TRẠNG");
        /* Set Column Header lên DefaultTableModel */
        model.setColumnIdentifiers(column);

        List<DANG_KI_HINH_THUC_XE> listDS = GUIXE_DTO.getListDKHTX();

        for (int i = 0; i < listDS.size(); i++) {
            DANG_KI_HINH_THUC_XE ht = (DANG_KI_HINH_THUC_XE) listDS.get(i);
            String hinhthuc = "";

            Vector row = new Vector();
            row.add(ht.getIdthe());
            row.add(ht.getBienSoXe());
            row.add(ht.getIdHinhThucGui().equals("1") ? "NGÀY" : "THÁNG");
            row.add(ht.getNgayDK());
            row.add(ht.getNgayHH());
            row.add(ht.getTienDaThu());
            row.add(ht.getIdtinhtrang().equalsIgnoreCase("CGH") ? "CHỜ GIA HẠN" : ht.getIdtinhtrang().equalsIgnoreCase("DH") ? "ĐÃ HỦY" : "KÍCH HOẠT");

            model.addRow(row);

        }
        jtbDS.setModel(model);
    }

    private void showDATA(String text) {
        DefaultTableModel model = new DefaultTableModel();
        model.setRowCount(0);

        /* Tạo mới Vector chứa Column Header */
        Vector column = new Vector();
        column.add("MA THẺ");
        column.add("BIỂN SỐ XE");
        column.add("HÌNH THỨC");
        column.add("NGAY DANG KI");
        column.add("NGAY HET HAN");
        column.add("TIỀN ĐÃ THU");
        column.add("TÌNH TRẠNG");
        /* Set Column Header lên DefaultTableModel */
        model.setColumnIdentifiers(column);

        List<DANG_KI_HINH_THUC_XE> listDS = GUIXE_DTO.getListSearch(text);

        for (int i = 0; i < listDS.size(); i++) {
            DANG_KI_HINH_THUC_XE ht = (DANG_KI_HINH_THUC_XE) listDS.get(i);
            String hinhthuc = "";

            Vector row = new Vector();
            row.add(ht.getIdthe());
            row.add(ht.getBienSoXe());
            row.add(ht.getIdHinhThucGui().equals("1") ? "NGÀY" : "THÁNG");
            row.add(ht.getNgayDK());
            row.add(ht.getNgayHH());
            row.add(ht.getTienDaThu());
            row.add(ht.getIdtinhtrang().equalsIgnoreCase("CGH") ? "CHỜ GIA HẠN" : ht.getIdtinhtrang().equalsIgnoreCase("DH") ? "ĐÃ HỦY" : "KÍCH HOẠT");

            model.addRow(row);

        }
        jtbDS.setModel(model);
    }

}
